This is makeindex, version 2.16 [MiKTeX 25.4].
Scanning style file ./VorlageAbschlussarbeiten.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file VorlageAbschlussarbeiten.acn....done (98 entries accepted, 0 rejected).
Sorting entries....done (697 comparisons).
Generating output file VorlageAbschlussarbeiten.acr....done (53 lines written, 0 warnings).
Output written in VorlageAbschlussarbeiten.acr.
Transcript written in VorlageAbschlussarbeiten.alg.
